name: CI

on: [pull_request]

jobs:
  build:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]
        python-version: [ '3.8', '3.9', '3.10', '3.11', '3.12', 'pypy-3.8' ]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install wheel
      run: pip install wheel
    - name: Build package
      run: python setup.py install
    - name: Run tests
      run: python tests.py
    - name: Run mypy tests
      run: python mypy_run.py
